### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by KlayMa527** [bytedance/SPTSv2#5]
In sptsv2.py line 60
out_label = self.vocab_embed(hs[2])[-1]**[:,1:text_length+1]**.reshape(src.size(0),-1,self.num_classes)

I know the purpose of this code is to extract the predicted text, but why is the index here using [:, 1: text_length+1]? What is the special meaning of index 1 here? Use center point annotation in the code, should we start with 2. If bezier is used for annotation, it needs to be modified here.

**Comment by zhangjx123** [comment]
q: why using [:, 1: text_length+1]；
a: because the first output is location y, which is not important in text recognition. if using bezier annotation, 1 should be modified to 15.

**Comment by KlayMa527** [comment]
I'm still a bit confused。
If we use the center point as the annotation, the first two outputs of the second decoder are x position and y position, followed by 25 text character. So I think we should use [:, 2: text_length+2,:] here. If we use bezier annotation,2 should be modified to 17.
I'm not sure if I'm interpreting this correctly, thank you very much for answering my next question.

**Comment by KlayMa527** [comment]
I still have some confusion.
If we use the center point as the annotation, the first 2 outputs of the second decoder are x position and y position, followed by 25 text characters. So I think we should use [:, 2: text_length+2] here.If  using bezier annotation, i think 2 should be modified to 16.
I'm not sure if I'm understanding this correctly, thank you very much for answering me.

**Comment by KlayMa527** [comment]
I appreciate your answer , I understand it.
