### ISSUE TITLE
Help wanted about NPTS

### ISSUE THREAD

**Issue by ZhengyaoFang** [bytedance/SPTSv2#6]
May I ask if you can provide an implementation code for NPTS? We would like to test it on some other datasets for research purpose. I guarantee any future work based on your code will reference your paper properly. Appreciate your help :)

**Comment by zhangjx123** [comment]
NPTS is not the main innovation of SPTSv2, you can refer to https://github.com/shannanyinxiang/SPTS, and erase the point gt in dataset file to reproduce NPTS.

**Comment by wjj1106** [comment]
@zhangjx123 Could you please provide the pretrained NPTS ckpt? Looking forward to your reply!
